import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#00476e",
        "primary-fixed-dim": "#9bccf6",
        "surface-dim": "#d2d9f4",
        "on-secondary-fixed": "#001d31",
        "inverse-on-surface": "#eef0ff",
        "inverse-primary": "#9bccf6",
        surface: "#faf8ff",
        "surface-container-highest": "#dae2fd",
        "tertiary-container": "#7e2a00",
        "on-tertiary-fixed-variant": "#7f2b00",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#004b73",
        "primary-fixed": "#cbe6ff",
        "surface-bright": "#faf8ff",
        "outline-variant": "#c1c7cf",
        "primary-container": "#0c4a6e",
        "secondary-container": "#5bb8fe",
        tertiary: "#591b00",
        "tertiary-fixed-dim": "#ffb599",
        "on-primary-fixed": "#001e30",
        "error-container": "#ffdad6",
        outline: "#72787f",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#370e00",
        "surface-variant": "#dae2fd",
        "on-primary-container": "#88b9e3",
        primary: "#00334f",
        "secondary-fixed": "#cce5ff",
        "secondary-fixed-dim": "#93ccff",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "surface-container": "#eaedff",
        "on-background": "#131b2e",
        "on-surface": "#131b2e",
        background: "#faf8ff",
        secondary: "#006398",
        "on-surface-variant": "#41474e",
        "tertiary-fixed": "#ffdbce",
        "surface-container-low": "#f2f3ff",
        "surface-tint": "#2f6388",
        "surface-container-high": "#e2e7ff",
        "on-primary-fixed-variant": "#0e4b6f",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ff9a72",
        error: "#ba1a1a",
        "inverse-surface": "#283044",
        tirua: {
          ocean: "#0A3656",
          wave: "#0284C7",
          sand: "#FBF7F0",
          terracotta: "#EA580C",
          forest: "#047857",
        },
      },
      spacing: {
        "space-md": "1rem",
        "margin-desktop": "3rem",
        "margin-tablet": "2rem",
        margin: "1rem",
        "gutter-desktop": "1.5rem",
        "space-xs": "0.25rem",
        "space-xl": "2.5rem",
        gutter: "1rem",
        "space-sm": "0.5rem",
        "space-lg": "1.5rem",
      },
      fontFamily: {
        "label-sm": ["Libre Baskerville", "Manrope", "serif"],
        "headline-xl": ["Libre Baskerville", "Epilogue", "serif"],
        "headline-lg-mobile": ["Libre Baskerville", "Epilogue", "serif"],
        "body-md": ["Libre Baskerville", "Manrope", "serif"],
        "label-md": ["Libre Baskerville", "Manrope", "serif"],
        "headline-lg": ["Libre Baskerville", "Epilogue", "serif"],
        "body-lg": ["Libre Baskerville", "Manrope", "serif"],
        "body-sm": ["Libre Baskerville", "Manrope", "serif"],
        "label-lg": ["Libre Baskerville", "Manrope", "serif"],
        "headline-sm": ["Libre Baskerville", "Epilogue", "serif"],
        "headline-xl-mobile": ["Libre Baskerville", "Epilogue", "serif"],
        "headline-md": ["Libre Baskerville", "Epilogue", "serif"],
      },
      fontSize: {
        "label-sm": [
          "10px",
          { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "700" },
        ],
        "headline-xl": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "body-md": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.015em", fontWeight: "700" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-lg": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "700" },
        ],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-xl-mobile": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "800" },
        ],
        "headline-md": ["22px", { lineHeight: "28px", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
